#160617639 Commenting on articles
andela/ah-frontend-lannister pull request #17
Opened 2018-11-15 14:50 UTC by kimbugp

#### What does this PR do?
- allow a user to comment on an article 
- allow a user to reply to comments on an article
#### Description of Task to be completed?
- when viewing an article a logged user is allowed to comment on it.
#### How should this be manually tested?
- login in HERE( ) and click on this URL( )
#### What are the relevant pivotal tracker stories?
- #160617639(https://www.pivotaltracker.com/story/show/160617639)
#### Screenshots (if appropriate)
- comments page view
<img width="1034" alt="screen shot 2018-11-15 at 17 41 01" src="https://user-images.githubusercontent.com/39520700/48560354-aefdb580-e8fe-11e8-9148-68dee8b7abea.png">
- adding a comment's view
<img width="1094" alt="screen shot 2018-11-15 at 17 42 11" src="https://user-images.githubusercontent.com/39520700/48560384-bde46800-e8fe-11e8-8137-58b95f7ec9b6.png">
- edit and delete functions view
<img width="1090" alt="screen shot 2018-11-15 at 17 49 26" src="https://user-images.githubusercontent.com/39520700/48560445-dce2fa00-e8fe-11e8-81f0-ce4075baa2a7.png">

2018-11-15 17:39 UTC, LehruAngela requested changes

2018-11-15 17:39 UTC, LehruAngela commented on src/views/commentsViews/commentsCard.js
> +  <React.Fragment>
Change this `React.Fragment` to just `Fragment` by destructuring it the way you would for `Component`

2018-11-15 19:39 UTC, kimbugp commented on src/views/commentsViews/commentsCard.js
> +  <React.Fragment>
Noted

2018-11-16 06:27 UTC, LehruAngela requested changes

2018-11-16 06:27 UTC, LehruAngela commented on src/__tests__/articleTests/comments.Test/commentComponents.js
> +import React from "react";
Have a different folder for comments instead of putting them in the articleTests folder, also when naming folders, use the camelCase convention

2018-11-16 06:27 UTC, LehruAngela commented on src/__tests__/auth/socialAuthActions.test.js
>  import { BASEURL } from "../../actions/authActions";
Import the BASE URL from the appUrls such as to have one single source of truth, also remove the index.js from the authActions and let all files import the BASE URL from the appUrls file

2018-11-16 06:27 UTC, LehruAngela commented on src/actions/actionTypes.js
> +export const CREATE_THREAD="CREATE_THREAD";
Add your actions to the ACTION_TYPE dictionary, and use the exported ACTION_TYPE to call your actions, so as to have code consistency

2018-11-16 06:41 UTC, LehruAngela commented
Transfer the `components/login.js` file to `components/auth/` directory

2018-11-16 07:04 UTC, LehruAngela commented
Also for your login feature, transfer your login url from appUrls/urls.js to appUrls/index.js and refactor accordingly

2018-11-16 07:23 UTC, kimbugp commented
@LehruAngela, I have  made the requested changes

2018-11-16 07:38 UTC, LehruAngela requested changes

2018-11-16 07:38 UTC, LehruAngela commented on src/assets/comment/comment.scss
> +}
Add a new line at end of file

2018-11-16 08:37 UTC, merged