#160617650 List Bookmarked articles
andela/ah-frontend-lannister pull request #21
Opened 2018-11-19 16:01 UTC by kcharles52

#### What does this PR do?
- Enables users to view a list of articles they have bookmarked
#### Description of Task to be completed?
- Enable authenticated users to view bookmarked articles
#### How should this be manually tested?
- When you click on profile picture on the navbar a drop-down menu appears. 
- Select bookmarks
#### What are the relevant pivotal tracker stories?
[#160617650]

2018-11-20 09:58 UTC, LehruAngela requested changes

2018-11-20 09:58 UTC, LehruAngela commented on src/views/bookmark/bookmarkArticleView.js
> +    <React.Fragment>
Change `React.Fragment` to just `Fragment` by destructuring it the way you would do for `Component`

2018-11-20 09:58 UTC, LehruAngela commented on src/views/bookmark/bookmarkArticleView.js
> +          <div className="readTime dtTab">3 min read</div>
Why is the dateTime and readTime static? Let it be dynamic as you did for the articleAuthor

2018-11-20 14:09 UTC, kcharles52 commented on src/views/bookmark/bookmarkArticleView.js
> +    <React.Fragment>
I have changed it

2018-11-21 07:53 UTC, LehruAngela commented
Add screenshots for this task here @kcharles52

2018-11-21 12:42 UTC, LehruAngela commented
Rebase with develop @kcharles52

2018-11-22 08:52 UTC, LehruAngela commented
Rebase with develop @kcharles52

2018-11-22 10:18 UTC, merged