#160617642 tagging articles
andela/ah-frontend-lannister pull request #27
Opened 2018-11-21 15:14 UTC by zaabu

#### What does this PR do?
- This PR implements tagging functionality. This enables authors to create tags for the articles that they create.
-It also enables users to categorize articles by a certain tag.

#### Description of Task to be completed?

Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. Tagging allows for organization and or categorization of content.

#### How should this be manually tested?

- Enter a comma-separated string of words when creating an article and the words will be stored as tags
- Visit an article and you should be able to view tags for that article.
-Click the tags at the end of the article and you should be redirected to a page that shows articles under that tag.

#### Screenshots

Creating tags
<img width="1227" alt="screen shot 2018-11-21 at 18 12 24" src="https://user-images.githubusercontent.com/20440510/48850196-2af17500-edb9-11e8-8f35-51251381e9cf.png">

Viewing tags on an article

<img width="994" alt="screen shot 2018-11-21 at 18 12 45" src="https://user-images.githubusercontent.com/20440510/48850214-36dd3700-edb9-11e8-9728-2e57ca3f139e.png">

Viewing articles under a given tag

<img width="1102" alt="screen shot 2018-11-21 at 18 12 55" src="https://user-images.githubusercontent.com/20440510/48850248-49577080-edb9-11e8-9d5e-f33445e29e97.png">

2018-11-22 08:41 UTC, LehruAngela requested changes

2018-11-22 08:41 UTC, LehruAngela commented on src/actions/actionTypes.js
> +export const VIEW_ARTICLES_UNDER_TAG = "VIEW_ARTICLES_UNDER_TAG";
Declare your action in the ACTION_TYPE dict

2018-11-22 08:41 UTC, LehruAngela commented on src/views/articles/viewArticle.js
> +
Remove empty lines of code, ensure you do that in all your files

2018-11-22 08:41 UTC, LehruAngela commented on src/assets/articleAssets/demo2.scss
> +
Separate the tag styles in a different file, and rename `demo2.scss` to a more descriptive file name

2018-11-22 08:44 UTC, LehruAngela commented
Add a tag title or something along those lines on the `view all articles for a tag page` so as to identify which tag under which the articles are being rendered. @zaabu, Also write tests

2018-11-22 13:27 UTC, zaabu commented on src/assets/articleAssets/demo2.scss
> +
I have resolved this @LehruAngela

2018-11-22 13:27 UTC, zaabu commented on src/views/articles/viewArticle.js
> +
I have resolved this @LehruAngela

2018-11-22 13:27 UTC, zaabu commented on src/actions/actionTypes.js
> +export const VIEW_ARTICLES_UNDER_TAG = "VIEW_ARTICLES_UNDER_TAG";
I have resolved this @LehruAngela  by declaring VIEW_ARTICLES_UNDER_TAG under ACTION_TYPE

2018-11-23 08:09 UTC, LehruAngela requested changes

2018-11-23 08:09 UTC, LehruAngela commented on src/assets/articleAssets/tags.scss
> +
Remove empty lines of code, and leave one empty line at end of file, ensure to do this in all files

2018-11-23 08:11 UTC, LehruAngela commented
Rebase with develop @zaabu

2018-11-23 08:24 UTC, zaabu commented on src/assets/articleAssets/tags.scss
> +
I have resolved this @LehruAngela

2018-11-23 10:08 UTC, merged